### ISSUE TITLE
Improve: Enable ON/OFF switch of attaching a title header

### ISSUE THREAD

**Issue by TatsuyaIse** [weseek/growi#324]
## TODO
- [ ]  Enable ON/OFF switch of attaching a title header to the first line when creating a new page.
  - This is an application global setting.

**Comment by sils-jk** [comment]
- [ ]  Switch ON/OFF of attach or not title header to the first line when creating a new page.

=>
- [ ]  Enable ON/OFF switch of attaching a title header to the first line when creating a new page.
