### ISSUE TITLE
Request: Add attach button to editor tool bar

### ISSUE THREAD

**Issue by yuki-takei** [weseek/growi#4133]
# Informations
**Is your feature request related to a problem? Please describe.**

Currently, user can attach files by clicking the button at the bottom of the editor pane.  
But it is hard to find for some users.

![image](https://user-images.githubusercontent.com/1638767/129045153-ef366167-5e75-4227-bb0a-6fced760a2ec.png)

# Solution

- Add a button to open dialog to choose file to the editor tool bar

![image](https://user-images.githubusercontent.com/1638767/129044863-95701bad-cc9f-47d7-b32d-d54f4fe8854d.png)

# TODO
- [ ] `CodeMirrorEditor.jsx`
  - [ ] Add a button in `getNavbarItems`
  - [ ] Fire a new event when clicking like `onMarkdownHelpButtonClicked`
- [ ] `Editor.jsx`
  - [ ] Handle the new event that is implemented in above
