### ISSUE TITLE
Request: Support Elasticserach 7

### ISSUE THREAD

**Issue by inductor** [weseek/growi#4437]
## Informations
**Is your feature request related to a problem? Please describe.**
Elasticsearch 6 already is EOL

**Comment by yuki-takei** [comment]
# TODO

- [ ] [GW-7600 [es7] @elastic/elasticsearch を使って ES6 での正常動作を確認する](https://youtrack.weseek.co.jp/issue/GW-7600)
- [ ] [GW-7601 [es7] Elasticsearch 7 に接続し、全ての機能を利用できる](https://youtrack.weseek.co.jp/issue/GW-7601)
- [ ] [GW-7607 [es7] cleanup](https://youtrack.weseek.co.jp/issue/GW-7607)
